version: '3.8'

services:
  shadowsocks:
    build: .
    container_name: ss-vpn
    restart: always
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    environment:
      - SS_PASSWORD=YourStrongPassword123!
      - SS_PORT=8388
      - SS_METHOD=aes-256-gcm
      - RENDER_URL=https://priy-vpn.onrender.com
    volumes:
      - ./config.json:/etc/shadowsocks-libev/config.json
