services:
  - type: web
    name: shadowsocks-vpn
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SS_PASSWORD
        value: 0Penupno2@priye5
      - key: SS_PORT
        value: 8388
      - key: SS_METHOD
        value: aes-256-gcm
      - key: RENDER_URL
        value: https://YOUR-APP-NAME.onrender.com
